version: '3.1'

services:
  test_db:
    image: postgres:15.4
    restart: always
    hostname: test_db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-consent-db
    ports:
      - 5434:5432
  test_audit_db:
    image: postgres:15.4
    restart: always
    hostname: test_audit_db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-audit-db
    ports:
      - 5435:5432


